/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.AirporTaxiScheduling.view;

import ec.edu.espe.AirporTaxiScheduling.controller.TraveldbController;
import ec.edu.espe.AirporTaxiScheduling.model.TaxiDriver;
import ec.edu.espe.AirporTaxiScheduling.model.Travel;
import ec.edu.espe.AirporTaxiScheduling.model.Traveler;
import ec.edu.espe.AirporTaxiScheduling.model.TravelerPayment;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Yaranga,Progress Team, DCCO-ESPE
 */
public class FrmAccounting extends javax.swing.JFrame {

    TravelerPayment travelerPayment = new TravelerPayment();
    TraveldbController dataBaseManager = new TraveldbController();

    String uri = "mongodb+srv://lyaranga:tortilla@espe2210-oopsw7996.77wv341.mongodb.net/?retryWrites=true&w=majority";
    String databaseName = "AirportTaxiScheduling";
    String collectionName = "Travels";

    /**
     * Creates new form frmAccounting
     */
    public FrmAccounting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAccounting = new javax.swing.JPanel();
        btnBACK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblTravels = new javax.swing.JTable();
        btnWiewTravels = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOutstanding = new javax.swing.JTextField();
        btmCreatePDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBACK.setText("<REGRESAR");
        btnBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBACKActionPerformed(evt);
            }
        });

        jLabel1.setText("CONTABILIDAD");

        jtblTravels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Conductor", "Pasajero", "Direccion", "Fecha", "Precio", "Pagado"
            }
        ));
        jtblTravels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblTravelsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblTravels);

        btnWiewTravels.setText("Ver las carreras existentes");
        btnWiewTravels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWiewTravelsActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de dinero cobrado:");

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Saldo pendiente a cobrar: ");

        txtOutstanding.setEditable(false);
        txtOutstanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutstandingActionPerformed(evt);
            }
        });

        btmCreatePDF.setText("Crear PDF");
        btmCreatePDF.setEnabled(false);
        btmCreatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCreatePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountingLayout = new javax.swing.GroupLayout(pnlAccounting);
        pnlAccounting.setLayout(pnlAccountingLayout);
        pnlAccountingLayout.setHorizontalGroup(
            pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountingLayout.createSequentialGroup()
                .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountingLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBACK)
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(pnlAccountingLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWiewTravels)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAccountingLayout.createSequentialGroup()
                                .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAccountingLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAccountingLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtOutstanding, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(132, 132, 132)
                                .addComponent(btmCreatePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlAccountingLayout.setVerticalGroup(
            pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountingLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBACK)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addComponent(btnWiewTravels)
                .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountingLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOutstanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmCreatePDF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAccounting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAccounting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBACKActionPerformed
        // TODO add your handling code here:
        AirportTaxiScheduling airportTaxiScheduling;
        airportTaxiScheduling = new AirportTaxiScheduling();
        this.setVisible(false);
        airportTaxiScheduling.setVisible(true);
    }//GEN-LAST:event_btnBACKActionPerformed

    private void jtblTravelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblTravelsMouseClicked

    }//GEN-LAST:event_jtblTravelsMouseClicked

    private void btnWiewTravelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWiewTravelsActionPerformed
btmCreatePDF.setEnabled(true);
        float totalPayed = 0;
        float outsB = 0;
        totalPayed = viewTravels(totalPayed);
        outsB = calculateOutstandingBalance(outsB);
        txtTotal.setText(Float.toString(totalPayed));
        txtOutstanding.setText(Float.toString(outsB));
    }//GEN-LAST:event_btnWiewTravelsActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtOutstandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutstandingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutstandingActionPerformed

    private void btmCreatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCreatePDFActionPerformed
        MessageFormat header = new MessageFormat("Accouting of travels");
        MessageFormat footer = new MessageFormat(" Total: "+txtTotal.getText()+" Outstanding Balance: "+txtOutstanding.getText()+" page {0,number,integer}");

        try {
           jtblTravels.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btmCreatePDFActionPerformed

    private float viewTravels(float totalPayed) {
        cleanForm();
        dataBaseManager = TraveldbController.connectToDatabase(uri, databaseName, dataBaseManager);
        ArrayList<Travel> travelsView = new ArrayList<Travel>();
        String[] titles = {"Id", "Conductor", "Pasajero", "Direccion", "Fecha", "Precio", "Pagado"};
        String[] travelsString = new String[7];
        DefaultTableModel tableOfTravels = new DefaultTableModel(null, titles);
        TraveldbController.load(travelsView, dataBaseManager.getDatabase(), collectionName);

        for (int i = 0; i < travelsView.size(); i++) {
            travelsString[0] = "" + travelsView.get(i).getId() + "";
            travelsString[1] = "" + travelsView.get(i).getDriver() + "";
            travelsString[2] = "" + travelsView.get(i).getTraveler() + "";
            travelsString[3] = "" + travelsView.get(i).getAddress() + "";
            travelsString[4] = "" + travelsView.get(i).getDateOfOcurrence() + "";
            travelsString[5] = "" + travelsView.get(i).getPrice() + "";
            travelsString[6] = "" + String.valueOf(travelsView.get(i).isPayed()) + "";
            tableOfTravels.addRow(travelsString);
            if (travelsView.get(i).isPayed() == true) {
                totalPayed += (travelsView.get(i).getPrice());
            }

        }

        jtblTravels.setModel(tableOfTravels);
        jtblTravels.setDefaultEditor(Object.class, null);
        return totalPayed;
    }
    
    private float calculateOutstandingBalance(float outsB){
        dataBaseManager = TraveldbController.connectToDatabase(uri, databaseName, dataBaseManager);
        ArrayList<Travel> travelsView = new ArrayList<Travel>();
        TraveldbController.load(travelsView, dataBaseManager.getDatabase(), collectionName);
        for (int i = 0; i < travelsView.size(); i++) {
            
            if (travelsView.get(i).isPayed() == false) {
                outsB += (travelsView.get(i).getPrice());
            }
        }
        return outsB;
    }

    private void cleanForm() {
        DefaultTableModel tableOfTravels = new DefaultTableModel();
        jtblTravels.setModel(tableOfTravels);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAccounting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAccounting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCreatePDF;
    private javax.swing.JButton btnBACK;
    private javax.swing.JButton btnWiewTravels;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblTravels;
    private javax.swing.JPanel pnlAccounting;
    private javax.swing.JTextField txtOutstanding;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
